name: build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - cluster
          - web-red
          - web-green
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build image
      uses: docker/build-push-action@v4
      with:
        context: ${{ matrix.module }}
        push: false
        platforms: linux/amd64
        load: true
        tags: |
          ghcr.io/ckotzbauer/kubernetes-showcase/${{ matrix.module }}
