name: reusable-release

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      folder:
        required: true
        type: string
      platforms:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      REPO_ACCESS:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  release:
    permissions:
      id-token: write
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.REPO_ACCESS }}

      - name: Build image
        uses: ckotzbauer/actions-toolkit/docker@0.36.0
        with:
          ghcr-password: ${{ secrets.DOCKER_PASSWORD }}
          context: ${{ inputs.folder }}
          push: true
          sign: false
          platforms: ${{ inputs.platforms }}
          build-args: version=${{ inputs.version }}
          tags: |
            ghcr.io/ckotzbauer/kubernetes-showcase/${{ inputs.image }}:${{ inputs.version }}
            ghcr.io/ckotzbauer/kubernetes-showcase/${{ inputs.image }}:latest
